config/routes.rb
Rails.application.routes.draw do
  
  get 'maps/index'

  get 'favorite_relationships/create'

  get 'favorite_relationships/destroy'

  root   'static_pages#home'
  
  post '/guest_log_in', to: 'sessions#new_guest'

  get    '/help',    to: 'static_pages#help'
  
  get    '/about',   to: 'static_pages#about'
  
  get    '/contact', to: 'static_pages#contact'
  
  get    '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  get    'maps/index',  to: 'maps#index'
  
  resources :users do
    member do 
      get :following, :followers, :likes
    end 
  end 
  
    
  
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :posts, only: [:show, :content, :title, :create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorite_relationships, only: [:create, :destroy]
  
  resources :maps, only: [:index]
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @post = current_user.posts.build 
      @feed_items = current_user.feed.paginate(page: params[:page]).search(params[:search])
    end 
  end

  def help
  end
  
  def about
  end
  
  def contact
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<!doctype html>
<head>
  <meta charset="UTF-8">
  <script type="text/javascript" src="title.js"></script>
  <link rel="stylesheet" type="text/css" href="custom.scss">
</head>
<body>
　

  
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="post_form">
        <%= render 'shared/post_form' %>
      </section>
    </aside>
    
    
    
    <div class="col-md-8">
      <h3>投稿一覧</h3>
      <%= render 'shared/search' %>
      <div class="search">
      <%= render 'shared/feed' %>
      </div>
    </div>
  </div>
<% else %>
  
  <div class="jumbotron-extend">
  <div class="fluid-box"> 
  <div class="container fluid-box-inner">
  <div class="container-fluid">
    
  <div class="box">
  <div class="bgImg src1"></div>
  <div class="bgImg src2"></div>
  <div class="bgImg src3"></div>
  <div class="bgImg src4"></div>
  <div class="bgImg src5"></div>
  <div class="bgImg src6"></div>
  <div class="bgImg src7"></div>
  <div class="boxString">
  <div class="text-focus-in">
  

    <h1>
     <%= link_to "日本", root_path, class: "titlelogo" %><%= link_to "カルト", root_path, class: "titlelogogradation" %><%= link_to "案内", root_path, class: "titlelogo" %>
    </h1>
    
    <h2>
      B級スポットやカルトな観光地を共有しよう
    </h2>
    
    <div style="text-align: center;">
      
    <h3 class="btn">
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-default center-block" %>
    <%= link_to "登録はコチラ", signup_path, class: "btn btn-lg btn-default center-block" %>
    <%= link_to "ゲストログイン", guest_log_in_path, method: :post, class: "btn btn-lg btn-default center-block" %>
    </h3>
    
    
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>
  </body>
  
  
<% end %>