config/routes.rb
Rails.application.routes.draw do
  
  get 'maps/index'

  get 'favorite_relationships/create'

  get 'favorite_relationships/destroy'

  root   'static_pages#home'
  
  post '/guest_log_in', to: 'sessions#new_guest'

  get    '/help',    to: 'static_pages#help'
  
  get    '/about',   to: 'static_pages#about'
  
  get    '/contact', to: 'static_pages#contact'
  
  get    '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  get    'maps/index',  to: 'maps#index'
  
  resources :users do
    member do 
      get :following, :followers, :likes
    end 
  end 
  
    
  
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :posts, only: [:show, :content, :title, :create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorite_relationships, only: [:create, :destroy]
  
  resources :maps, only: [:index]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %> 
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
  
  
  
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :title, placeholder: "タイトルをいれてください" %>
    <%= f.text_area :content, placeholder: "どんな場所ですか？" %>
    <%= f.text_area :address, placeholder:"住所、場所をいれてください" %>
    <%= f.submit "投稿する", class: "button" %>

  </div>
  
<span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    <%= f.file_field :picture %>
  </span>
<% end %>

<script type="text/javascript">
  $('#post_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_search.html.erb
<!-- 投稿検索機能 -->
  <p>投稿検索</p>
  <%= form_tag root_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "投稿検索", :name => nil %>
  </p>
  <% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
  
  <!-- いいね機能 -->
  <a href="<%= likes_user_path(@user) %>">
    <strong id="likes" class="stat">
      <%= @user.likes.count %>
    </strong>
    いいね！
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "マイプロフィール", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>