config/routes.rb
Rails.application.routes.draw do
  
  get 'maps/index'

  get 'favorite_relationships/create'

  get 'favorite_relationships/destroy'

  root   'static_pages#home'
  
  post '/guest_log_in', to: 'sessions#new_guest'

  get    '/help',    to: 'static_pages#help'
  
  get    '/about',   to: 'static_pages#about'
  
  get    '/contact', to: 'static_pages#contact'
  
  get    '/signup',  to: 'users#new'
  
  get    '/login',   to: 'sessions#new'
  
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
  get    'maps/index',  to: 'maps#index'
  
  resources :users do
    member do 
      get :following, :followers, :likes
    end 
  end 
  
    
  
  
  resources :account_activations, only: [:edit]
  
  resources :password_resets, only: [:new, :create, :edit, :update]
  
  resources :posts, only: [:show, :content, :title, :create, :destroy]
  
  resources :relationships, only: [:create, :destroy]
  
  resources :favorite_relationships, only: [:create, :destroy]
  
  resources :maps, only: [:index]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<head>
<link rel="stylesheet" type="text/css" href="custom.scss">
</head>
<header class="navbar navbar-fixed-top navbar-header">
  
  <div class="container">
    <%= link_to "日本", root_path, class: "logo" %><%= link_to "カルト", root_path, class: "logogradation" %><%= link_to "案内", root_path, class: "logo" %>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark mt-3 mb-3">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", help_path %></li>
        <li><%= link_to "ユーザー", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          </header>
          
        <% else %>
        <header class="navbar navbar-fixed-top navbar-header">
        <div class="container">
         <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "ホーム", root_path, class: "logo-btn" %></li>
         <li><%= link_to "ヘルプ", help_path, class: "logo-btn" %></li>
         </ul>
         </div>
          </header>
        <% end %>
        
      </ul>
    </nav>
  </div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
       <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
      
      
    </div>
  </body>
</html>